server:
  port: 8070

application:
  version: AppVersion 1.0.0
  title: thejoeun company

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 329640614505-ghojacmncovs2ncb41l3obppcr557d1k.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
    user:
      name: user
      password: 1234
  thymeleaf:
    cache: false
  sql:
    init:
      mode: always  # default 상태는 never
      encoding: utf-8
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb5         # mariadb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234


  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    show-sql: true # java코드로 짠 sql을
    defer-datasource-initialization: true # data.sql 사용을 위해서 필수적으로 등록
    properties:
      hibernate:
        format_sql: true  # sql문 pretty하게 보여줌
        use_sql_comments: true   # 사용중인 sql의 commnet를 보여줌  예)
    generate-ddl: false # 굉장히 중요함, 데이터가 사라질수 있음  // true, false  //값이 없다면 기본값은 false
    # 테이블을 생성함 create;  ddl(drop, create), dml(CRUD)
    hibernate:
      ddl-auto: create  # ddl(create, drop)  // 위 generate-ddl 과 같이 설정할 때는 hibernate가 우선순위를 가짐; generate-ddl 무시됨

mvc:
  view:
    prefix: /WEB-INF/view/
    suffix: .jsp
devtools:
  livereload:
    enabled: true


logging:
  level:
    org:
      hibernate:   # info, trace
        orm:
          jdbc:
            bind: trace     #hibernate에서 ? 값 보기
        SQL: debug
        #        type: trace
        type:
          decriptor:
            sql: trace
#    root: trace

jwt:
  issuer: jwt1@abc.com
  secret_key: 1234

